{% set name = "grafeas" %}
{% set version = "1.1.3" %}
{% set sha256 = "7044f716a19d07336d2d1692dd82fe8799fa6984cec9ad95a9b79cfdfb8c8ce8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.21.0,<3.0.0dev
    - proto-plus >=1.4.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - grafeas.grafeas_v1

about:
  home: https://github.com/googleapis/python-grafeas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Grafeas API client library
  description: An implementation of the Grafeas API, which stores, and enables querying and retrieval of critical metadata about all of your software artifacts.

  doc_url: https://googleapis.dev/python/grafeas/latest/index.html
  dev_url: https://github.com/googleapis/python-grafeas

extra:
  recipe-maintainers:
    - parthea
